name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this profiles README with latest blog post list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          feed_list: "https://dev.to/feed/ngschmidt"
